packages/desktop_drop/lib/desktop_drop_web.dart
fixes #51 by accessing item.lastModified in favor of item.lastModifiedDate, when available. This mitigates a crash in Safari.
=> Fix issue MixinNetwork/flutter-plugins#51

packages/desktop_drop/CHANGELOG.md, packages/desktop_drop/example/pubspec.lock, packages/desktop_drop/example/windows/flutter/generated_plugins.cmake, packages/desktop_drop/macos/Classes/DesktopDropPlugin.swift, packages/desktop_drop/pubspec.yaml
fix #72
use `draggingPasteboard.readObjects` instead `NSDraggingInfo.enumerateDraggingItems` to retrieve `NSURL` form drag info.
=> refactor performDragOperation on macOS

packages/pasteboard/example/pubspec.lock, packages/pasteboard/example/windows/flutter/generated_plugins.cmake, packages/pasteboard/lib/pasteboard.dart, packages/pasteboard/windows/pasteboard_plugin.cpp
A new property "html" to retrieve from the clipboard the html text from CF_HTML (49380) field.
The HTML Clipboard Format description: https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa767917(v=vs.85)
I didn't change the pubspec.lock and generated_plugins.cmake files, don't know why there are some changes.
=> HTML Clipboard Format support

packages/pasteboard/pubspec.yaml
Fixes the problem, described in this issue - https://github.com/MixinNetwork/flutter-plugins/issues/121
=> fix js version dependence

packages/desktop_multi_window/CHANGELOG.md, packages/desktop_multi_window/example/lib/main.dart, packages/desktop_multi_window/example/pubspec.lock, packages/desktop_multi_window/lib/desktop_multi_window.dart, packages/desktop_multi_window/lib/src/channels.dart, packages/desktop_multi_window/lib/src/window_controller.dart, packages/desktop_multi_window/lib/src/window_controller_impl.dart, packages/desktop_multi_window/macos/Classes/FlutterMultiWindowPlugin.swift, packages/desktop_multi_window/macos/Classes/FlutterWindow.swift, packages/desktop_multi_window/macos/Classes/MultiWindowManager.swift, packages/desktop_multi_window/pubspec.yaml
This PR adds the ability to control whether a created window can be resized or not by calling the `resizable()` function. Passing `false` to the function will result in a window that cannot be resized. 
There is no need to explicitly set a window to be resizable - windows will be resizable by default.
Here is an example of a non-resizable window:
```dart
final window = await DesktopMultiWindow.createWindow(jsonEncode({
'args1': 'Sub window',
'args2': 100,
'args3': true,
'business': 'business_test',
}));
window
..setFrame(const Offset(0, 0) & const Size(1280, 720))
..center()
..setTitle('Another window')
..resizable(false)
..show();
```
Removing the `..resizable(false)` call will result in a window that *is* resizable.
***Please note*** that this feature has only been implemented for …
=> [desktop_multi_window] Added the `resizable` function (macOS only)

packages/mixin_logger/README.md, packages/mixin_logger/lib/mixin_logger.dart, packages/mixin_logger/lib/src/write_log_to_file_io.dart, packages/mixin_logger/lib/src/write_log_to_file_web.dart, packages/mixin_logger/test/mixin_logger_test.dart
If initLogger is not awaited the following log messages using f.e.  i() are not written.
LogFileManager.init() is already returning a Future, but initLogger doesn't await on it.
That's changed now.
=> [mixin-logger] make initLogger return Future<void> instead of void

packages/win_toast/windows/wintoastlib.cpp, packages/win_toast/windows/wintoastlib.h
As discussed here https://bytemeta.vip/repo/YehudaKremer/msix/issues/118
MSIX packaged Applications show toast notifications with the wrong Application Name.
=> stopped using aumi for toast notifications MSIX packaged Apps

packages/desktop_drop/android/build.gradle, packages/desktop_drop/example/android/app/build.gradle, packages/desktop_drop/example/android/build.gradle, packages/desktop_drop/example/android/gradle/wrapper/gradle-wrapper.properties
This is causing some issues in builds that use this package as a transitive dependency. I'm not sure how it's coming up since it's just the example folder, but this bump in versions should fix the issue. More info here https://github.com/GetStream/stream-chat-flutter/issues/1372
=> Update to later versions of Kotlin and Gradle

packages/desktop_drop/macos/Classes/DesktopDropPlugin.swift
When used in conjunction with plugins that replace the `FlutterViewController` in macOS Flutter apps, such as [`flutter_acrylic`][1] and [`macos_ui`][2], `desktop_drop` causes some trackpad gestures to break. I found that pinch-to-zoom no longer worked, but there could be other weird behavior I missed.
This PR fixes the issue by recursively searching the view controller hierarchy starting at `MainFlutterWindow.contentViewController` for a `FlutterViewController` to attach its child view to.
[1]: https://github.com/alexmercerind/flutter_acrylic/blob/88019e9ed841354d3af02e31c138a133e350a0d6/example/macos/Runner/MainFlutterWindow.swift#L8
[2]: https://github.com/GroovinChip/macos_ui/blob/d6d4a27f3f4c2ad28aeb1c77126cdc6884979736/example/macos/Runner/MainFlutterWindow.swift#L40
=> [desktop_drop] Fix broken gestures when used with modified MainFlutterWindow

packages/desktop_webview_window/lib/src/webview.dart, packages/desktop_webview_window/lib/src/webview_impl.dart, packages/desktop_webview_window/windows/web_view.cc
The API definitions for
Future<String?> postWebMessageAsString(String webMessage)
Future<String?> postWebMessageAsJson(String webMessage)
should be
Future<void> postWebMessageAsString(String webMessage)
Future<void> postWebMessageAsJson(String webMessage)
=> [desktop_webview_window] Correct API Definition of post webmessages

packages/desktop_multi_window/windows/desktop_multi_window_plugin.cpp
Currently a createWindow call on windows will cause app crash. We should add null check to createWindow args.
=> [desktop_multi_window] fix windows createWindow crash when arguments is null

packages/desktop_multi_window/linux/flutter_window.cc
Handle close button click and destroy sub-window explicitly.
Possible related issue: https://github.com/MixinNetwork/flutter-plugins/issues/231
Better solutions are welcome.
=> [desktop_multi_window] fix to not close the entire application when a sub-window is closed

packages/desktop_webview_window/lib/src/webview.dart, packages/desktop_webview_window/lib/src/webview_impl.dart, packages/desktop_webview_window/windows/web_view_window_plugin.cc, packages/desktop_webview_window/windows/webview_window.cc, packages/desktop_webview_window/windows/webview_window.h
This PR adds the functionality to bring the webview window to the foreground under windows
=> [desktop-webview-window] Bring Webview Window to Foreground

packages/desktop_drop/windows/desktop_drop_plugin.cpp
close #278 
fix desktop_drop_plugin.cpp(150): warning C4701: potentially uninitialized local variable 'hwnd' used
=> [desktop_drop] fix windows build warning C4701

packages/desktop_drop/android/build.gradle, packages/desktop_drop/android/gradle/wrapper/gradle-wrapper.properties, packages/desktop_drop/android/src/main/AndroidManifest.xml, packages/desktop_drop/example/android/app/build.gradle, packages/desktop_drop/example/android/app/src/main/AndroidManifest.xml, packages/desktop_drop/example/android/build.gradle, packages/desktop_drop/example/android/gradle/wrapper/gradle-wrapper.properties
This PR adds `namespace` to the plugin's `build.gradle` so that projects which use AGP8+ can use `desktop_drop`.
See [Breaking change: namespace required in module-level build script](https://developer.android.com/build/releases/past-releases/agp-8-0-0-release-notes) for detailed information.
Other updates (including example):
- bump to latest kotlin version
- use latest pre 8 AGP and Gradle
Tested on devices running Android 8.1 and Android 14 beta.
=> [desktop_drop] add namespace for Android platform

packages/desktop_drop/macos/Classes/DesktopDropPlugin.swift
This makes desktop_drop work even if Flutter is embedded into another application. In that case, the Flutter NSWindow is not the application main window.
=> macOS: Obtain NSWindow from FlutterPluginRegistrar

packages/desktop_drop/.metadata, packages/desktop_drop/example/lib/main.dart, packages/desktop_drop/example/web/index.html, packages/desktop_drop/lib/desktop_drop.dart, packages/desktop_drop/lib/desktop_drop_web.dart, packages/desktop_drop/lib/src/channel.dart, packages/desktop_drop/lib/src/drop_item.dart, packages/desktop_drop/lib/src/drop_target.dart, packages/desktop_drop/lib/src/events.dart, packages/desktop_drop/lib/src/web_drop_item.dart
**My issue:**
I'm developing an application that uses the drag and drop on the desktop and web. On desktop it works perfectly well, when I drop a folder, for example, I can use the `Directory` object from the `dart:io` and iterates from all the folder's content.
But on the web we don't have the `dart:io` library, so how could I do this folder content getting?
I searched for many ways to do that, using the blob URL that is generated, using the FileReader and some other ways, nothing worked. The only way possible to do that was getting the folder content when I drop the folder, using the `DataTransferItem` from the [`DataTransferItemList`](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItemList).
**The solution**
Using the `DataTransferItem` I can determine if the item is a …
=> [desktop_drop] Drag and drop folder on web now returns the folder's content

packages/desktop_webview_window/linux/CMakeLists.txt, packages/desktop_webview_window/linux/webview_window.cc
In my last PR #311, I made sure that it runs correct functions for backward compatibility.
But I came to know that for both webkit 4.0 and 4.1 after version 2.40.0 these functions are deprecated. Hence added the code to correctly run right snippet.
=> [FIX] Use deprecated functions on versions older than 2.40

packages/desktop_webview_window/.gitignore, packages/desktop_webview_window/README.md, packages/desktop_webview_window/example/lib/main.dart, packages/desktop_webview_window/example/macos/Podfile, packages/desktop_webview_window/example/macos/Podfile.lock, packages/desktop_webview_window/example/macos/Runner.xcodeproj/project.pbxproj, packages/desktop_webview_window/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, packages/desktop_webview_window/example/pubspec.lock, packages/desktop_webview_window/example/windows/flutter/CMakeLists.txt, packages/desktop_webview_window/lib/src/cookie.dart, packages/desktop_webview_window/lib/src/webview.dart, packages/desktop_webview_window/lib/src/webview_impl.dart, packages/desktop_webview_window/linux/CMakeLists.txt, packages/desktop_webview_window/linux/desktop_webview_window_plugin.cc, packages/desktop_webview_window/linux/webview_window.cc, packages/desktop_webview_window/linux/webview_window.h, packages/desktop_webview_window/macos/Classes/DesktopWebviewWindowPlugin.swift, packages/desktop_webview_window/macos/Classes/WebViewLayoutController.swift, packages/desktop_webview_window/macos/desktop_webview_window.podspec, packages/desktop_webview_window/windows/utils.cc, packages/desktop_webview_window/windows/utils.h, packages/desktop_webview_window/windows/web_view.cc, packages/desktop_webview_window/windows/web_view.h, packages/desktop_webview_window/windows/web_view_window_plugin.cc
Closes #125
This PR adds ability to get stored cookies for the webview in all desktop platforms (Windows, MacOS, Linux).
Linux has limited support, as it can only get the webview's active `uri`'s cookies at the moment.
Other platforms has full support to get cookies for all domains available.
=> [desktop_webview_window] add support for getting cookies

packages/desktop_drop/android/build.gradle, packages/desktop_drop/example/android/app/build.gradle, packages/desktop_drop/example/android/build.gradle, packages/desktop_drop/example/pubspec.lock
Require Kotlin `1.7.10` instead of `1.9.10` for compatibility since we don't use new Kotlin language features.
The Kotlin version set in `packages/desktop_drop/android/build.gradle` represents the minimum Kotlin version for
the user project.
Steps to reproduce:
- Create a new blank Flutter project
- Add `desktop_drop` plugin
- Try to run/build the Android project using `flutter run` or with a Gradle task instead
You will get this build failure:
```
┌─ Flutter Fix ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project requires a newer version of the Kotlin Gradle plugin.                                                                                           │
│ Find the …
```
=> chore(desktop_drop): use Kotlin 1.7.10 instead of 1.9.10 for compatibility

packages/win_toast/windows/CMakeLists.txt
Error logs:
`win_toast_plugin.obj : error LNK2019: unresolved external symbol WINRT_IMPL_RoGetActivationFactory referenced in function "struct winrt::hresult __cdecl winrt::impl::get_runtime_activation_factory_impl<1>(struct winrt::param::hstring const &,struct winrt::guid const &,void * *)" (??$get_runtime_activation_factory_impl@$00@impl@winrt@@YA?AUhresult@1@AEBUhstring@param@1@AEBUguid@1@PEAPEAX@Z) [D:\a\1\s\build\windows\x64\plugins\win_toast\win_toast_plugin.vcxproj]
DesktopNotificationManagerCompat.obj : error LNK2001: unresolved external symbol WINRT_IMPL_RoGetActivationFactory [D:\a\1\s\build\windows\x64\plugins\win_toast\win_toast_plugin.vcxproj]
win_toast_plugin.obj : error LNK2019: unresolved external symbol WINRT_IMPL_RoOriginateLanguageException referenced in function …
=> fix(win_toast): build fail on latest visual studio
